version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: "postgres:15.1"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=queuetask

  # for testing:
  rabbitmq-test:
    image: rabbitmq:management
    ports:
      - "5673:5672"
      - "15673:15672"
  db-test:
    image: "postgres:15.1"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=queuetask