CREATE TABLE resource_download_request (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(300) NOT NULL,
    status VARCHAR(30) NOT NULL
);

CREATE TABLE resource (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER,
    content TEXT,
    CONSTRAINT fk_resource_download_request
        FOREIGN KEY(request_id)
        REFERENCES resource_download_request(id)
);